[package]
name = "lumina-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
lumina-core = { path = "../lumina-core" }
lumina-renderer = { path = "../lumina-renderer" }
lumina-schema = { path = "../lumina-schema" }
serde_json = { workspace = true }

[[bench]]
name = "lumina_bench"
harness = false
