#!/usr/bin/env bash
# Regenerates every SVG in this directory. Run from the repo root:
#   docs/architecture/gen-diagrams.sh
# Requires: graphviz (dot), cargo, python3.
set -euo pipefail
cd "$(dirname "$0")/../.."
OUT=docs/architecture

# 1. Crate dependency graph — generated from cargo metadata (never hand-edit).
python3 - "$OUT/dependency-graph.dot" <<'PY'
import json, subprocess, sys

meta = json.loads(subprocess.run(
    ["cargo", "metadata", "--format-version", "1", "--no-deps"],
    check=True, capture_output=True, text=True).stdout)
members = {p["name"]: p for p in meta["packages"]}
layers = {  # visual layering only; edges come from real manifest data
    "lumina-schema": "0 data", "lumina-core": "1 logic", "lumina-text": "1 logic",
    "lumina-renderer": "2 pixels", "lumina-export": "3 io", "lumina-server": "4 apps",
    "lumina-wasm": "4 apps", "lumina-cli": "4 apps", "lumina-bench": "4 apps",
}
lines = [
    "// GENERATED by gen-diagrams.sh — do not edit by hand.",
    "digraph crates {",
    '  rankdir=BT; bgcolor="transparent";',
    '  node [shape=box, style="rounded,filled", fillcolor="#1E3A5F", fontcolor=white,'
    '        color="#4A90D9", fontname="Helvetica", fontsize=12];',
    '  edge [color="#4A90D9"];',
]
for name in members:
    lines.append(f'  "{name}";')
for name, pkg in members.items():
    for dep in pkg["dependencies"]:
        if dep["name"] in members:
            lines.append(f'  "{name}" -> "{dep["name"]}";')
# same-layer alignment
by_layer = {}
for n, l in layers.items():
    if n in members:
        by_layer.setdefault(l, []).append(n)
for layer in sorted(by_layer):
    row = " ".join(f'"{n}";' for n in by_layer[layer])
    lines.append(f"  {{ rank=same; {row} }}")
lines.append("}")
open(sys.argv[1], "w").write("\n".join(lines) + "\n")
PY
dot -Tsvg "$OUT/dependency-graph.dot" -o "$OUT/dependency-graph.svg"

# 2. Hand-maintained pipeline diagrams (edit the .dot, rerun this script).
for f in scene-pipeline render-pipeline event-pipeline export-pipeline; do
  dot -Tsvg "$OUT/$f.dot" -o "$OUT/$f.svg"
done

# 3. Copy into the book so docs/src/architecture.md can embed them.
mkdir -p docs/src/diagrams
cp "$OUT"/*.svg docs/src/diagrams/

echo "OK: $(ls "$OUT"/*.svg | wc -l) SVGs regenerated in $OUT/ (+ copied to docs/src/diagrams/)"
