[package]
name = "lumina-schema"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
schemars = { workspace = true }
glam = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
